# Site settings
title: alexanderfrankel
email: alexxander.frankel@gmail.com
description: "BEWARE. You are entering inside the mind of Alexander Lewis Frankel. All content is his own. He will not take responsibility for changes in thought process, personal opinion, or any trauma that you may experience."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
