# Site settings
title: alexanderfrankel
email: alexxander.frankel@gmail.com
description: "This is a safe place. A place of expression, self-awareness, creativity, honesty, opinion, and peace."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
